export const tableData = [
  {
    id: 1,
    age: 82,
    first_name: "John",
    last_name: "Doe",
    email: "dharling0@rediff.com",
    gender: "Female",
    phone: "232(152)707-0110",
    occupation: "Financial Advisor",
  },
  {
    id: 2,
    age: 89,
    first_name: "Jane",
    last_name: "Doe",
    email: "bllewellin1@example.com",
    gender: "Male",
    phone: "420(169)218-1769",
    occupation: "Marketing Assistant",
  },
  {
    id: 3,
    age: 28,
    first_name: "Mary",
    last_name: "Jane",
    email: "rcarbry2@prlog.org",
    gender: "Polygender",
    phone: "86(958)204-4491",
    occupation: "Mechanical Systems Engineer",
  },
  {
    id: 4,
    age: 20,
    first_name: "Bernardo",
    last_name: "Harry",
    email: "bhacun3@xinhuanet.com",
    gender: "Male",
    phone: "86(974)709-5254",
    occupation: "Research Assistant IV",
  },
  {
    id: 5,
    age: 2,
    first_name: "Rock",
    last_name: "Latest",
    email: "egarstang4@miitbeian.gov.cn",
    gender: "Female",
    phone: "55(644)175-6748",
    occupation: "Business Systems Development Analyst",
  },
  {
    id: 6,
    age: 98,
    first_name: "Dian",
    last_name: "Cooper",
    email: "ddopson5@examiner.com",
    gender: "Female",
    phone: "51(186)560-8480",
    occupation: "Cost Accountant",
  },
  {
    id: 7,
    age: 17,
    first_name: "John",
    last_name: "Anderson",
    email: "cponter6@loc.gov",
    gender: "Female",
    phone: "1(941)734-6255",
    occupation: "Budget/Accounting Analyst II",
  },
  {
    id: 8,
    age: 85,
    first_name: "Valentine",
    last_name: "Crispin",
    email: "vcrispin7@dailymotion.com",
    gender: "Male",
    phone: "380(627)884-8734",
    occupation: "Project Manager",
  },
  {
    id: 9,
    age: 77,
    first_name: "Gill",
    last_name: "Richard",
    email: "gsutlieff8@engadget.com",
    gender: "Male",
    phone: "386(374)937-6305",
    occupation: "Recruiter",
  },
  {
    id: 10,
    age: 23,
    first_name: "Noreen",
    last_name: "Black",
    email: "nblick9@usa.gov",
    gender: "Female",
    phone: "998(884)893-6477",
    occupation: "Human Resources Manager",
  },
];
