import React, { useState } from "react";

import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";

import AddRoundedIcon from "@mui/icons-material/AddRounded";
import RemoveRoundedIcon from "@mui/icons-material/RemoveRounded";
import HelpCenterRoundedIcon from "@mui/icons-material/HelpCenterRounded";
import MenuBookRoundedIcon from "@mui/icons-material/MenuBookRounded";

const GUIDES = [
  {
    title: "How to Register",
    content: (
      <div className="space-y-4">
        <p>
          Follow these steps to initiate your access request for the SafeLanka
          ecosystem:
        </p>
        <ol className="list-decimal list-inside space-y-2 ml-2">
          <li>
            Access the <strong>Register</strong> portal from the main
            navigation.
          </li>
          <li>
            Provide your full legal name and official professional designation.
          </li>
          <li>
            Select your specific <strong>Police Division</strong> or Research
            Department.
          </li>
          <li>
            Upload a valid professional ID or enter your badge number for
            verification.
          </li>
          <li>
            Review the <strong>Terms of Service</strong> and click "Submit
            Application".
          </li>
        </ol>
        <p className="bg-primary/5 p-3 rounded-lg border-l-4 border-primary text-xs">
          <strong>Note:</strong> Double-check your email address, as approval
          notifications are sent via email.
        </p>
      </div>
    ),
  },
  {
    title: "How Admin Approval Works",
    content: (
      <div className="space-y-4">
        <p>
          To maintain the integrity of sensitive crime data, all accounts
          undergo a manual verification process:
        </p>
        <ol className="list-decimal list-inside space-y-2 ml-2">
          <li>
            <strong>Verification:</strong> System administrators cross-reference
            your details with official records.
          </li>
          <li>
            <strong>Status Update:</strong> You will receive an "Under Review"
            status initially.
          </li>
          <li>
            <strong>Access Grant:</strong> Once verified, your role-specific
            dashboard will be activated.
          </li>
          <li>
            <strong>Security Policy:</strong> Accounts inactive for 90 days may
            require re-approval to maintain security standards.
          </li>
        </ol>
      </div>
    ),
  },
  {
    title: "How to View Predictions",
    content: (
      <div className="space-y-4">
        <p>
          Once your dashboard is active, follow these steps to access AI
          insights:
        </p>
        <ol className="list-decimal list-inside space-y-2 ml-2">
          <li>
            Select the <strong>Predictions</strong> tab from the sidebar menu.
          </li>
          <li>
            Use the filter tool to choose a specific <strong>Date Range</strong>{" "}
            or <strong>Crime Category</strong>.
          </li>
          <li>
            Toggle the <strong>Hotspot View</strong> to see the geospatial
            density map.
          </li>
          <li>
            Click on specific divisions to view the{" "}
            <strong>Trend Forecast</strong> (Increase/Decrease percentage).
          </li>
          <li>
            Export visual reports using the "Download PDF" button for offline
            tactical meetings.
          </li>
        </ol>
      </div>
    ),
  },
  {
    title: "How to Interpret the Heatmap",
    content: (
      <div className="space-y-4">
        <p>
          The heatmap color-coding is based on probability scores generated by
          the Random Forest model:
        </p>
        <ul className="list-disc list-inside space-y-3 ml-2">
          <li>
            <span className="text-emerald-600 font-bold">
              Green (Safe Zone):
            </span>{" "}
            Historical data suggests a low probability of incident occurrence
            during the selected timeframe.
          </li>
          <li>
            <span className="text-amber-500 font-bold">
              Yellow (Caution Zone):
            </span>{" "}
            Moderate risk detected. Requires standard patrol frequency and
            observation.
          </li>
          <li>
            <span className="text-red-600 font-bold">Red (Critical Zone):</span>{" "}
            High probability of incident occurrence. Immediate tactical
            attention and preventive patrolling recommended.
          </li>
        </ul>
        <p className="italic text-slate-500 text-xs mt-2">
          *Heatmaps are updated periodically as new historical reports are
          ingested into the MySQL database.
        </p>
      </div>
    ),
  },
];

const FAQS = [
  {
    q: "Who can register for SafeLanka?",
    a: "Access is strictly limited to Sri Lanka Police officers, system admins, crime analysts, and authorized academic researchers with valid credentials.",
  },
  {
    q: "Why does admin approval matter?",
    a: "As the system contains sensitive crime pattern data, manual approval ensures that access is only granted to verified personnel, preventing unauthorized data exposure.",
  },
  {
    q: "Is the system accessible on mobile devices?",
    a: "Yes, the SafeLanka web platform is fully responsive and optimized for use on smartphones and tablets, allowing field officers to access heatmaps on the go.",
  },
  {
    q: "Does SafeLanka provide real-time crime data?",
    a: "No. SafeLanka is an advisory tool focused on long-term predictions and trend analysis. For live active incidents, please use the official Emergency Response Dispatch system.",
  },
];

const GuidePage = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggle = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="relative w-full pt-8 pb-20 px-6 bg-white dark:bg-slate-900 overflow-hidden">
      <div className="absolute top-0 right-0 w-96 h-96 bg-primary/5 rounded-full blur-[100px] pointer-events-none" />

      <div className="max-w-4xl mx-auto space-y-20 relative z-10">
        <div className="text-center">
          <Badge
            label="Documentation"
            className="mb-4 px-4 py-1 text-xs font-bold uppercase tracking-widest text-primary-500 bg-primary-500/10 border-none rounded-full"
          />
          <h1 className="text-5xl font-black text-slate-900 dark:text-white tracking-tight">
            User Guide
          </h1>
          <p className="mt-4 text-lg text-slate-600 dark:text-slate-400 max-w-2xl mx-auto leading-relaxed">
            This comprehensive guide provides the technical and operational
            instructions required to navigate the SafeLanka ecosystem.
          </p>
        </div>

        <div className="space-y-4">
          <div className="flex items-center gap-2 mb-6 text-slate-900 dark:text-white font-bold text-xl">
            <MenuBookRoundedIcon className="text-primary" />
            <h2>System Instructions</h2>
          </div>
          {GUIDES.map((item, index) => (
            <Card
              key={item.title}
              className={`transition-all duration-300 border border-slate-200 dark:border-slate-800 rounded-2xl overflow-hidden ${
                openIndex === index
                  ? "shadow-xl ring-1 ring-primary/20"
                  : "hover:shadow-md"
              }`}
            >
              <div
                className="p-6 cursor-pointer flex justify-between items-center group bg-white dark:bg-slate-900"
                onClick={() => toggle(index)}
              >
                <h3
                  className={`text-lg font-bold transition-colors ${
                    openIndex === index
                      ? "text-primary"
                      : "text-slate-900 dark:text-white"
                  }`}
                >
                  {item.title}
                </h3>
                <div
                  className={`w-8 h-8 rounded-full flex items-center justify-center transition-all ${
                    openIndex === index
                      ? "bg-primary-500 text-white"
                      : "bg-slate-100 dark:bg-slate-800 text-slate-500"
                  }`}
                >
                  {openIndex === index ? (
                    <RemoveRoundedIcon fontSize="small" />
                  ) : (
                    <AddRoundedIcon fontSize="small" />
                  )}
                </div>
              </div>

              {openIndex === index && (
                <div className="px-8 pb-8 pt-2 text-slate-600 dark:text-slate-400 bg-white dark:bg-slate-900 animate-in fade-in slide-in-from-top-2 duration-300">
                  <div className="h-px w-full bg-slate-100 dark:bg-slate-800 mb-6" />
                  <div className="text-base leading-relaxed">
                    {item.content}
                  </div>
                </div>
              )}
            </Card>
          ))}
        </div>

        <div className="pt-10">
          <div className="flex items-center gap-2 mb-8 text-slate-900 dark:text-white font-bold text-xl">
            <HelpCenterRoundedIcon className="text-primary" />
            <h2>Common Inquiries</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {FAQS.map((faq, index) => (
              <Card
                key={index}
                className="p-8 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm hover:shadow-lg transition-all flex flex-col gap-3"
              >
                <h4 className="text-lg font-bold text-slate-900 dark:text-white">
                  {faq.q}
                </h4>
                <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
                  {faq.a}
                </p>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default GuidePage;
